# Use this deployment if you plan to deploy your gRPC service to Cloud Endpoints using ESP
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: player-deployment
  labels:
    app: player-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: player-api
    spec:       
      containers:
      - name: player-api
        image: asia.gcr.io/minsoojunprj/player-api:v1 # replace PROJECT_ID
        imagePullPolicy: "Always"
        ports:
        - containerPort: 50051
        env:
        - name: PROJECTID
          value: "minsoojunprj" # replace PROJECT_ID
        - name: INSTANCE
          value: "demo-spanner" # replace INSTANCE
        - name: DATABASE
          value: "demo-grpc"  # replace DATABASE
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-S", "9000",
          "-a", "grpc://127.0.0.1:50051",
          "-s", "player.endpoints.minsoojunprj.cloud.goog", # replace PROJECT_ID
          "--rollout_strategy", "managed",
          "-z", " ",
        ]
        volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: nginx-ssl
            readOnly: true
        ports:
          - containerPort: 9000
      volumes:
      - name: nginx-ssl
        secret:
           secretName: nginx-ssl
